name: Update Version Badges

on:
  push:
    paths:
      - 'backend/requirements.txt'
      - 'frontend/package.json'
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          cd frontend && npm install

      - name: Get Python dependencies
        id: python-deps
        run: |
          echo "PYTHON_VERSION=$(python --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "FASTAPI_VERSION=$(pip show fastapi | grep Version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "POSTGRES_VERSION=$(grep 'psycopg2-binary' backend/requirements.txt | cut -d'=' -f3)" >> $GITHUB_OUTPUT

      - name: Get Node.js dependencies
        id: node-deps
        run: |
          echo "REACT_VERSION=$(node -p "require('./frontend/package.json').dependencies.react")" >> $GITHUB_OUTPUT

      - name: Update README badges
        run: |
          python scripts/update_badges.py
        env:
          PYTHON_VERSION: ${{ steps.python-deps.outputs.PYTHON_VERSION }}
          FASTAPI_VERSION: ${{ steps.python-deps.outputs.FASTAPI_VERSION }}
          POSTGRES_VERSION: ${{ steps.python-deps.outputs.POSTGRES_VERSION }}
          REACT_VERSION: ${{ steps.node-deps.outputs.REACT_VERSION }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update version badges"
          file_pattern: README.md
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 